### PR TITLE
KYLO-689 - Update docs for ranger config

### PR DESCRIPTION
**Pull request by jomach**
on the docs there is missing these configs.

### CODE REVIEW

**Comment by CalvinHartwell** [comment]
:thumbsup: looks good

**Comment by jomach** [comment]
@CalvinHartwell  Do you know for what are these for in ranger ?

**Comment by CalvinHartwell** [comment]
@jomach yeah, this is the config file for the Apache Ranger plugin, are you having issues? 

If so, you can open an issue on the Jira or I'm on IRC and slack.

**Comment by jomach** [comment]
@CalvinHartwell What is the irc or slack channel ?

**Comment by CalvinHartwell** [comment]
The best place to ask questions for support is here: https://groups.google.com/forum/#!forum/kylo-community

@jomach the slack channel is for ThinkBig/TD employees only I believe. 

There is also an unofficial IRC channel (#kylo) on freenode, but I'm on there but AFK. I would recommend creating a thread on the google group for now.

**Pull request merged**
