### PR TITLE
Update TroubleshootingandTips.rst

### PR DESCRIPTION
**Pull request by nicklonginow**

### CODE REVIEW

**Review by jagrutsharma — CHANGES_REQUESTED** [review]
The JAVA_HOME in existing instructions is being set in file /etc/hadoop/conf/hadoop-env.sh. To manage this via Ambari, it seems the right place to configure is: 
HDFS -> Configs -> Advanced -> advanced hadoop-env

Please check using this location.

**Comment by nicklonginow** [comment]
Just as a way of explanation... My first attempt was using the exact suggestion you make.  However, once that was done and I attempted to restart HDFS, YARN and MapReduce2 (as the UI recommended), they all failed to restart, with an error in the logs saying that the given JAVA_HOME was missing a trailing "/jre" in the path.  So, I added that trailing "/jre" to the path in the HDFS section, which allowed HDFS to start after a restart. But, then the Sqoop import reverted to its earlier failure mode (unable to find JDK).  It seems that the HDFS section wants to have a JRE, whereas the Sqoop code is wanting to have a JDK (as your original Troubleshooting document pointed out).  Once I returned the HDFS section of Ambari to the original settings (export JAVA_HOME={{java_home}}) and then made the JAVA_HOME change instead in the Sqoop section, then HDFS/YARN and MapReduce2 all started up after a restart, as did the Sqoop client.  And, then the import worked.  Perhaps I did the process wrong?  I just couldnt make it work the way you explain above here, with changes in the HDFS section.  Odd... yes.

**Comment by nicklonginow** [comment]
Good morning Jagrut – I updated the request with a comment, addressing your concern.  Please let me know if it is on the right track?  thanks

**Comment by jagrutsharma** [comment]
Thanks for providing explanation of your test. Changing the `sqoop-client` section of Ambari changes `sqoop-env.sh`, so providing the JDK location for `JAVA_HOME` is allowing Sqoop to find it. 

Since the documentation change only impacts Sqoop configuration, this looks fine.

**Comment by nicklonginow** [comment]
Sweet! Thanks Jagrut. My first contribution to Kylo!!! Small though it is….

**Pull request merged**
